ktor:
  development: true
  application:
    modules:
      - eu.tortitas.stash.ApplicationKt.module
  deployment:
    port: 5482
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "secret"

mail:
  host: ""
  username: ""
  password: ""
  from: ""

postgres:
  #url: "jdbc:postgresql://localhost:5432/stash"
  url: "jdbc:postgresql://db:5432/stash"
  user: "stash"
  password: "secret"
