ktor:
  development: true
  application:
    modules:
      - eu.tortitas.stash.ApplicationKt.module
  deployment:
    port: 5482
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "secret"

postgres:
  url: "jdbc:postgresql://localhost:5481/stash"
  user: "stash"
  password: "secret"
