name: Deploy

on:
  push:
    branches: ["production"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Copy application config from secrets
        env:
          APPLICATION_CONFIG_YAML: ${{ secrets.APPLICATION_CONFIG_YAML }}
        shell: bash
        run: |
          echo "$APPLICATION_CONFIG_YAML" > src/main/resources/application.yaml

      - name: Build
        run: ./gradlew buildFatJar

      - name: Build www
        run: |
          npm install --prefix www
          npm run --prefix www build

      - name: Create publish folder
        run: |
          mkdir -p publish/www
          cp build/libs/eu.tortitas.stash.stash-api-all.jar publish
          cp compose.yaml publish
          cp -r www/dist publish/www/dist
          cp .deploy/manager.sh publish

      # Public key is ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINB2yDOCpBdy0x3DHOaVHMCtpayJ72bFypGRw8rX3YO6 vgarciaf@hey.com
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "publish"
          REMOTE_HOST: ${{ secrets.DEPLOY_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_REMOTE_USER }}
          TARGET: ${{ secrets.DEPLOY_REMOTE_TARGET }}
          SCRIPT_AFTER: |
            cd ${{ secrets.DEPLOY_REMOTE_TARGET }}/publish
            docker-compose -f compose.yaml -p stash up -d
            ./manager.sh stop
            ./manager.sh start
